### ISSUE TITLE
Could you take a video about the codes and the steps?

### ISSUE THREAD

**Issue by resobyte** [tyuksel53/YukselA-Blog#1]
Hi bro, 
First of all, congratulations on your work.
Could you take a video about the codes?

**Comment by tyuksel53** [comment]
Hi @resobyte ,

I am glad you ask that. I haven't got much free time lately. In my free time i will add videos and gifs about the project. Don't worry

**Comment by ramazan** [comment]
Hi at all!

@tyuksel53 I am so excited to hear that!  

as he said @resobyte  we wanna watch development videos about this project!

Thanks!
